CREATE TABLE IF NOT EXISTS donor(
    id BIGSERIAL NOT NULL PRIMARY KEY,
	username  VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_username ON donor (username);