database: 
  driver: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5441
  db_name: "donor"
kafka:
  host: "localhost"
  port: 29092
batch_size: 10000
tables: ["test", "donor", "interceptor", "server", "drop table users", "users;drop table users; users"]
migration_path: "./migrations"
test_count_rows: 25000